### ISSUE TITLE
No `prisma new` command

### ISSUE THREAD

**Issue by matthewmueller** [prisma/next#12]
<img width="416" alt="Screen Shot 2019-06-10 at 12 40 52 PM" src="https://user-images.githubusercontent.com/170299/59174789-01ddd980-8b7d-11e9-89b2-e2b96656323c.png">

**Comment by schickling** [comment]
This is currently called `prisma init`. You can find the [proposed design here](https://www.figma.com/file/cRvu7bwRRC0zleOvtlTgmkOu/Prisma-CLI?node-id=613%3A0).

**Comment by matthewmueller** [comment]
Any chance we can consolidate on one word for "creating a new X"? Right now we have `init` and `create`. 

I'm not a huge fan of `init`, it's an abbreviation on `initialize` and we don't have any other abbreviations. e.g. `prisma gen`.

**Comment by schickling** [comment]
I'm fine with `prisma new`. (Gatsby is using `gatsby new` as well.)

Re `prisma lift create` / `prisma lift new`: Not a huge fan of `new` in this context though. I still feel like `prisma lift commit` could be a great fit as mental model. Thoughts?

**Comment by matthewmueller** [comment]
yah, it's less clear in the context for `prisma lift`. My only concern with `prisma lift commit` is that people will confuse up with push and down with pull.

**Comment by schickling** [comment]
I think since we can assume that every Prisma user is also using `git`, they are familiar with the `commit` concept and that it does **not** directly push/apply. I'd suggest testing this during the preview period and adjust it if it causes confusion. Agree?

**Comment by schickling** [comment]
There's now an initial version of `prisma init`.

Update on `prisma lift commit`: We've now opted for `prisma lift save`.
