### ISSUE TITLE
Error in query engine: Database creation error: Sqlite data source must point to an existing file.

### ISSUE THREAD

**Issue by schickling** [prisma/next#35]
![image](https://user-images.githubusercontent.com/1567498/59344002-616aef00-8d0d-11e9-98c3-2bbb7de268bb.png)

**Comment by sorenbs** [comment]
@timsuchanek - I just reproduced this.

Both `yarn` and `prisma2 generate` fails.

 If I run `prismas dev` first, then I can run `prismas generate` or `yarn` afterwards.

**Comment by timsuchanek** [comment]
Fixed in latest version.
