### ISSUE TITLE
Prisma Dev issues

### ISSUE THREAD

**Issue by sorenbs** [prisma/next#37]
@timsuchanek - here are various issues that are easily triggered using `prisma dev`:

### What I did

1. run `prisma dev`
2. change `Author.name` to `Author.names`
3. change it back

![image](https://user-images.githubusercontent.com/281337/59347512-1fde4200-8d15-11e9-8982-7b7e671e635b.png)

4. do it again

![image](https://user-images.githubusercontent.com/281337/59347562-47cda580-8d15-11e9-9213-24574fe891d1.png)

5. do it again - this time no issue
6. do it again - this time no issue
7. do it again:

![image](https://user-images.githubusercontent.com/281337/59347644-78154400-8d15-11e9-9772-6abf00ac8599.png)

**Comment by timsuchanek** [comment]
Should be fixed @sorenbs please try again.
