### ISSUE TITLE
`prisma dev` should not re-execute removed generator blocks

### ISSUE THREAD

**Issue by sorenbs** [prisma/next#42]
If I remove or comment out a generator block after starting `prisma dev`, they are still being executed:

![image](https://user-images.githubusercontent.com/281337/59359606-ef0b0680-8d2e-11e9-8558-c9eec390e4f4.png)

Conversely, a newly added generator block is not executed.

**Comment by timsuchanek** [comment]
@sorenbs should be fixed, plz confirm.
