### ISSUE TITLE
Demo doesn't work on CSB

### ISSUE THREAD

**Issue by schickling** [prisma/next#65]
![image](https://user-images.githubusercontent.com/1567498/59549537-763ec100-8f5f-11e9-809e-452575e6c842.png)

**Comment by timsuchanek** [comment]
@matthewmueller look in https://github.com/prisma/lift/tree/master/src

**Comment by matthewmueller** [comment]
Quick update on this one, I was able to get it working with the following steps:

1. yarn install prisma2
2. Download `prisma` and `migration-engine` manually for `linux-glibc` not `linux-musl`. 
2. The binaries from S3 aren't executable, so you need to do `chmod +x migration-engine` and `chmod +x prisma`
4. move newly downloaded prisma and migration-engine binaries into the prisma2 node_modules overriding the originals
5. Run `yarn prisma2 lift save` & `yarn prisma2 lift up`
6. Run `yarn prisma2 generate`
7. Run `yarn ts-node main.ts`

**Comment by matthewmueller** [comment]
@prisma/backend would it be possible to publish binary to S3?

Right now these URLs:

- https://s3-eu-west-1.amazonaws.com/prisma-native/alpha/latest/linux-glibc/prisma
- https://s3-eu-west-1.amazonaws.com/prisma-native/alpha/latest/linux-glibc/migration-engine

Have the following permissions:

```
-rw-r--r-- 1 m staff 20M Jun 15 21:12 prisma
-rw-r--r-- 1 m staff 11M Jun 16 10:26 migration-engine
```

`chmod +x prisma` will fix this, but I'd imagine the Rust compiler should do this for you.

Here's the right permission bits:

```
-rwxr-xr-x 1 m staff 20M Jun 15 21:12 prisma*
-rwxr-xr-x 1 m staff 11M Jun 16 10:26 migration-engine*
```

**Comment by matthewmueller** [comment]
Should be resolved by https://github.com/prisma/photon-js/pull/23
