### ISSUE TITLE
Rename field (data not required) migration does nothing

### ISSUE THREAD

**Issue by divyenduz** [prisma/next#7]
This change in the datamodel

<img width="219" alt="Screen Shot 2019-06-07 at 13 57 58" src="https://user-images.githubusercontent.com/746482/59104158-129a0f80-8931-11e9-8696-6553c7cd475d.png">

Lift CLI returns success with a weird "No statements inferrable." message

<img width="806" alt="Screen Shot 2019-06-07 at 13 59 17" src="https://user-images.githubusercontent.com/746482/59104170-2180c200-8931-11e9-8e49-62faf952e5cf.png">

And produces a migration with 0 applied and rolled back steps: 

```
  {
    "revision": 2,
    "name": "20190607135355-rename-token",
    "datamodel": "model User {\n    id Int @id\n    email String? @unique\n    meetup_id String @unique\n    groups Group[]\n    tokens Token[]\n}\n\nmodel Token {\n    id Int @id\n    provider Provider\n    access_token String?\n    refresh_token String?\n    user User?\n}\n\nmodel Group {\n    id Int @id\n    user User?\n}\n\nenum Provider {\n    MEETUP\n}",
    "status": "Success",
    "applied": 0,
    "rolled_back": 0,
    "datamodel_steps": "[{\"stepType\":\"CreateField\",\"model\":\"User\",\"name\":\"tokens\",\"type\":{\"Relation\":{\"to\":\"Token\",\"to_fields\":[],\"name\":\"TokenToUser\",\"on_delete\":\"None\"}},\"arity\":\"list\",\"isUnique\":false},{\"stepType\":\"DeleteField\",\"model\":\"User\",\"name\":\"token\"}]",
    "database_migration": "{\"steps\":[],\"rollback\":[]}",
    "errors": "[]",
    "started_at": "1559908550290",
    "finished_at": "1559908550292"
  }
```

**Comment by mavilein** [comment]
@divyenduz : what would you expect here? There is no need to do something on the database in that case. This is a relation field and has no direct counterpart in the db.

**Comment by divyenduz** [comment]
End to end, I anticipated my photon API to change from `token` to `tokens` and it did not happen for whatever reason! I am closing this for now but re-report it if I run into similar issue again.
