### ISSUE TITLE
Photon types of args in "update" incorrect

### ISSUE THREAD

**Issue by divyenduz** [prisma/next#8]
![image](https://user-images.githubusercontent.com/746482/59105548-72de8080-8934-11e9-9626-49eb1a22ccc3.png)

The types of input arguments look incorrect and I am able to put arbitrary fields in it.

Update: Tim told me to check the runtime, which would happen soon™.

**Comment by divyenduz** [comment]
Datamodel: 
https://github.com/divyenduz/footybot/pull/4/files#diff-e7f1f0f12bf119a4750d892b48e1822d

**Comment by matthewmueller** [comment]
Hmmmmmmmmm @timsuchanek, I think I got it working, but I'm not sure if I'm missing any cases:

**From:**

```
  update<T extends UserUpdateArgs>(
    args: Subset<T, UserUpdateArgs>,
  ): 'select' extends keyof T
    ? PromiseLike<UserGetPayload<ExtractUserUpdateArgsSelect<T>>>
    : UserClient<User>

export declare type UserUpdateArgs = {
  select?: UserSelect
  data: UserUpdateInput
  where: UserWhereUniqueInput
}
```

**To:**

```ts
  update(
    args: UserUpdateArgs,
  ): 'select' extends keyof UserUpdateArgs
    ? PromiseLike<UserGetPayload<ExtractUserUpdateArgsSelect<UserUpdateArgs>>>
    : UserClient<User>

export declare type UserUpdateArgs = {
  select?: Partial<UserSelect>
  data: Partial<UserUpdateInput>
  where: Partial<UserWhereUniqueInput>
}
```

**Comment by timsuchanek** [comment]
Can't reproduce with TS 3.5.1 
![image](https://user-images.githubusercontent.com/1094804/59565951-9c488c00-9059-11e9-8a1f-474c8d00b747.png)

**Comment by matthewmueller** [comment]
@divyenduz can you double check again? I was no longer able to reproduce it either.

**Comment by divyenduz** [comment]
Me neither.
