### ISSUE TITLE
prisma2 init  - migration engine error

### ISSUE THREAD

**Issue by Gbahaa** [prisma/next#95]
Instaled prisma2 and tried to start a project.

```prisma2 init```
- choose MySql docker (used before for prisma 1 project on localhost)  :heavy_check_mark:
- connect to database  :heavy_check_mark:
- choose the database default@default or even "New schema " :x:

error:

 ```Error in lift engine for rpc convertDmmfToDml: /home/USER_NAME/.nvm/versions/node/v8.10.0/lib/node_modules/prisma2/migration-engine: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory```

prisma2@0.0.84
ubuntu16.04
node8.10

any thoughts?

**Comment by dpetrick** [comment]
Please install libssl `apt update && apt install libssl1.1`.

**Comment by Gbahaa** [comment]
Thank you. Solved. 

This issue is because libssl 1.1 is required for prisma so make sure to have it installed in advance.

**Comment by Epicteto** [comment]
Is there a solution for local development on Windows machines?
